#spring:
#    datasource:
#        username:root
#         password:Vmysql1234@
#         url:jdbc:mysql://localhost:3306/javatech
#         driver-class-name:com.mysql.cj.jdbc.Driver
#jpa:
#  show-sql:true
#  hibernate:
#    ddl-auto:update
#    propertirs.hibernate.dialect:org.hibernate.dialect.MySQLDialect
#         